service: sample

provider:
  memorySize: 128
  name: aws
  region: ap-northeast-1
  runtime: nodejs4.3
  timeout: 300

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
plugins:
  - serverless-run-function-plugin
  - custom-serverless-plugin
